Script started on Tue Sep  9 18:44:26 2014
[?1034hbash-4.1$ cd ~/os161/root
bash-4.1$ sys616[K[K[K161 kernel/Users/nethrakumar/os161/asst0/run.script
sys161: System/161 release 1.14, compiled Sep  4 2014 10:34:58

OS/161 base system version 1.11
Copyright (c) 2000, 2001, 2002, 2003
   President and Fellows of Harvard College.  All rights reserved.

Put-your-group-name-here's system version 0 (ASST0 #1)

Cpu is MIPS r2000/r3000
336k physical memory available
Device probe...
lamebus0 (system main bus)
emu0 at lamebus0
ltrace0 at lamebus0
ltimer0 at lamebus0
hardclock on ltimer0 (100 hz)
beep0 at ltimer0
rtclock0 at ltimer0
lrandom0 at lamebus0
random0 at lrandom0
lhd0 at lamebus0
lhd1 at lamebus0
lser0 at lamebus0
con0 at lser0
pseudorand0 (virtual)

OS/161 kernel [? for menu]: p /sbin/powere off
Operation took 0.000159280 seconds
OS/161 kernel [? for menu]: Shutting down.
The system is halted.
sys161: 346926858 cycles (4598696k, 18u, 342328144i)
sys161: 2060 irqs 6 exns 0r/0w disk 19r/695w console 8r/0w/3m emufs 0r/0w net
sys161: Elapsed real time: 13.855458 seconds (25.039 mhz)
sys161: Elapsed virtual time: 13.877074320 seconds (25 mhz)
bash-4.1$ ec[Kxitr[K
exit

Script done on Tue Sep  9 18:45:51 2014
